@startuml
class Document {
  content_id
  locale
}

class Edition {
  number
}

class Status {
  state
}

note left
  Has past statuses
  One status
  Potentially a next status
end note

Document -- Edition : current
Document .. Edition : live
Edition -- Status : current
Edition .. Status : next
Edition *-- Status : past

object document_1 {
  id = "1"
  content_id = "12345-12345-12345"
  locale = "en"
}

object edition_1 {
  id = "1"
  number = "1"
}

object e1_past_status {
  state = "draft"
  pending = false
}

object e1_status {
  state = "submitted"
  pending = false
}

object document_2 {
  id = "2"
  content_id = "45678-45678-45678"
  locale = "en"
}

object edition_2 {
  id = "2"
  number = "1"
}

object e2_status {
  state = "submitted"
  pending = false
}

object e2_next_status {
  state = "published"
  pending = true
}

document_1 -- edition_1: current
edition_1 .. e1_past_status
edition_1 -- e1_status
document_2 -- edition_2: current
edition_2 -- e2_status
edition_2 -- e2_next_status
@enduml
