version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    allow:
      # Security updates
      - dependency-name: brakeman
        dependency-type: direct
      # Internal gems
      - dependency-name: "govuk*"
        dependency-type: direct
      - dependency-name: gds-api-adapters
        dependency-type: direct
      - dependency-name: gds-sso
        dependency-type: direct
      - dependency-name: govspeak
        dependency-type: direct
      - dependency-name: plek
        dependency-type: direct
      - dependency-name: rubocop-govuk
        dependency-type: direct
      # Framework gems
      - dependency-name: factory_bot_rails
        dependency-type: direct
      - dependency-name: rails
        dependency-type: direct
      - dependency-name: rspec-rails
        dependency-type: direct
      - dependency-name: sassc-rails
        dependency-type: direct
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    allow:
      # Internal packages
      - dependency-name: accessible-autocomplete
        dependency-type: direct
      - dependency-name: markdown-toolbar-element
        dependency-type: direct
      - dependency-name: miller-columns-element
        dependency-type: direct
      - dependency-name: paste-html-to-govspeak
        dependency-type: direct
      - dependency-name: stylelint-config-gds
        dependency-type: direct
      # Framework packages
      - dependency-name: jasmine-browser-runner
        dependency-type: direct
      - dependency-name: jasmine-core
        dependency-type: direct
      - dependency-name: standard
        dependency-type: direct
      - dependency-name: stylelint
        dependency-type: direct
