api_version: 2
defaults:
  allowed_semver_bumps:
    - patch
    - minor
  auto_merge: true
  update_external_dependencies: true
overrides:
  - dependency: rails # should be upgraded manually, see https://docs.publishing.service.gov.uk/manual/keeping-software-current.html#rails
    auto_merge: false
