AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - bin/**/*
    - config.ru
    - db/schema.rb
    - tmp/**/*
    - node_modules/**/*

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'lib/tasks/**/*.rake'
    - 'spec/**/*.rb'
    - 'db/migrate/*.rb'

Rails:
  Enabled: true

Rails/InverseOf:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - config/**/*

Style/StringLiterals:
  Enabled: true

Style/TrailingCommaInHashLiteral:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  Enabled: true

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Rails/DynamicFindBy:
  Whitelist:
    - find_by_param
    - find_by_document

Rails/SaveBang:
  Enabled: true

Style/DateTime:
  Enabled: true
