@startuml
class Revision {
  number
}

class Content {
  title
  summary
  contents
  update_type
  change_note
}

class Tagging {
  tags
}

class Image {
  filename
  crop
  alt_text
  caption
  credit
}

class Blob {
  key
  content_type
}

class AssetManagerState {
  value
  asset_manager_path
}

Revision -down- Content
Revision -down- Tagging
Revision *--* Image: all
Revision .down. Image: lead >
Image -down- AssetManagerState
Image -down- Blob
@enduml
